/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2' in SOPC Builder design 'nios_system'
 * SOPC Builder design path: /home/tk-student/tse_tutorial/nios_system.sopcinfo
 *
 * Generated: Wed Jan 08 15:28:09 CET 2020
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00102820
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "small"
#define ALT_CPU_DATA_ADDR_WIDTH 0x15
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00080020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INST_ADDR_WIDTH 0x15
#define ALT_CPU_NAME "nios2"
#define ALT_CPU_RESET_ADDR 0x00080000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00102820
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "small"
#define NIOS2_DATA_ADDR_WIDTH 0x15
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00080020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INST_ADDR_WIDTH 0x15
#define NIOS2_RESET_ADDR 0x00080000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_ETH_TSE
#define __ALTERA_NIOS2_QSYS


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x103900
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x103900
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x103900
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios_system"


/*
 * descriptor_memory0 configuration
 *
 */

#define ALT_MODULE_CLASS_descriptor_memory0 altera_avalon_onchip_memory2
#define DESCRIPTOR_MEMORY0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DESCRIPTOR_MEMORY0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DESCRIPTOR_MEMORY0_BASE 0x101000
#define DESCRIPTOR_MEMORY0_CONTENTS_INFO ""
#define DESCRIPTOR_MEMORY0_DUAL_PORT 0
#define DESCRIPTOR_MEMORY0_GUI_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEMORY0_INIT_CONTENTS_FILE "nios_system_descriptor_memory0"
#define DESCRIPTOR_MEMORY0_INIT_MEM_CONTENT 1
#define DESCRIPTOR_MEMORY0_INSTANCE_ID "NONE"
#define DESCRIPTOR_MEMORY0_IRQ -1
#define DESCRIPTOR_MEMORY0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DESCRIPTOR_MEMORY0_NAME "/dev/descriptor_memory0"
#define DESCRIPTOR_MEMORY0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DESCRIPTOR_MEMORY0_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEMORY0_READ_DURING_WRITE_MODE "DONT_CARE"
#define DESCRIPTOR_MEMORY0_SINGLE_CLOCK_OP 0
#define DESCRIPTOR_MEMORY0_SIZE_MULTIPLE 1
#define DESCRIPTOR_MEMORY0_SIZE_VALUE 4096
#define DESCRIPTOR_MEMORY0_SPAN 4096
#define DESCRIPTOR_MEMORY0_TYPE "altera_avalon_onchip_memory2"
#define DESCRIPTOR_MEMORY0_WRITABLE 1


/*
 * descriptor_memory1 configuration
 *
 */

#define ALT_MODULE_CLASS_descriptor_memory1 altera_avalon_onchip_memory2
#define DESCRIPTOR_MEMORY1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DESCRIPTOR_MEMORY1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DESCRIPTOR_MEMORY1_BASE 0x100000
#define DESCRIPTOR_MEMORY1_CONTENTS_INFO ""
#define DESCRIPTOR_MEMORY1_DUAL_PORT 0
#define DESCRIPTOR_MEMORY1_GUI_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEMORY1_INIT_CONTENTS_FILE "nios_system_descriptor_memory1"
#define DESCRIPTOR_MEMORY1_INIT_MEM_CONTENT 1
#define DESCRIPTOR_MEMORY1_INSTANCE_ID "NONE"
#define DESCRIPTOR_MEMORY1_IRQ -1
#define DESCRIPTOR_MEMORY1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DESCRIPTOR_MEMORY1_NAME "/dev/descriptor_memory1"
#define DESCRIPTOR_MEMORY1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DESCRIPTOR_MEMORY1_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEMORY1_READ_DURING_WRITE_MODE "DONT_CARE"
#define DESCRIPTOR_MEMORY1_SINGLE_CLOCK_OP 0
#define DESCRIPTOR_MEMORY1_SIZE_MULTIPLE 1
#define DESCRIPTOR_MEMORY1_SIZE_VALUE 4096
#define DESCRIPTOR_MEMORY1_SPAN 4096
#define DESCRIPTOR_MEMORY1_TYPE "altera_avalon_onchip_memory2"
#define DESCRIPTOR_MEMORY1_WRITABLE 1


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x103900
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * main_memory configuration
 *
 */

#define ALT_MODULE_CLASS_main_memory altera_avalon_onchip_memory2
#define MAIN_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MAIN_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MAIN_MEMORY_BASE 0x80000
#define MAIN_MEMORY_CONTENTS_INFO ""
#define MAIN_MEMORY_DUAL_PORT 0
#define MAIN_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define MAIN_MEMORY_INIT_CONTENTS_FILE "nios_system_main_memory"
#define MAIN_MEMORY_INIT_MEM_CONTENT 1
#define MAIN_MEMORY_INSTANCE_ID "NONE"
#define MAIN_MEMORY_IRQ -1
#define MAIN_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MAIN_MEMORY_NAME "/dev/main_memory"
#define MAIN_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MAIN_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define MAIN_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define MAIN_MEMORY_SINGLE_CLOCK_OP 0
#define MAIN_MEMORY_SIZE_MULTIPLE 1
#define MAIN_MEMORY_SIZE_VALUE 307200
#define MAIN_MEMORY_SPAN 307200
#define MAIN_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define MAIN_MEMORY_WRITABLE 1


/*
 * main_memory configuration as viewed by sgdma_rx0_m_write
 *
 */

#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_BASE 0x80000
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_CONTENTS_INFO ""
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_DUAL_PORT 0
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_INIT_CONTENTS_FILE "nios_system_main_memory"
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_INIT_MEM_CONTENT 1
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_INSTANCE_ID "NONE"
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_IRQ -1
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_NAME "/dev/main_memory"
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_SINGLE_CLOCK_OP 0
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_SIZE_MULTIPLE 1
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_SIZE_VALUE 307200
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_SPAN 307200
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_RX0_M_WRITE_MAIN_MEMORY_WRITABLE 1


/*
 * main_memory configuration as viewed by sgdma_rx1_m_write
 *
 */

#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_BASE 0x80000
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_CONTENTS_INFO ""
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_DUAL_PORT 0
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_INIT_CONTENTS_FILE "nios_system_main_memory"
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_INIT_MEM_CONTENT 1
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_INSTANCE_ID "NONE"
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_IRQ -1
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_NAME "/dev/main_memory"
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_SINGLE_CLOCK_OP 0
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_SIZE_MULTIPLE 1
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_SIZE_VALUE 307200
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_SPAN 307200
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_RX1_M_WRITE_MAIN_MEMORY_WRITABLE 1


/*
 * main_memory configuration as viewed by sgdma_tx0_m_read
 *
 */

#define SGDMA_TX0_M_READ_MAIN_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_TX0_M_READ_MAIN_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_TX0_M_READ_MAIN_MEMORY_BASE 0x80000
#define SGDMA_TX0_M_READ_MAIN_MEMORY_CONTENTS_INFO ""
#define SGDMA_TX0_M_READ_MAIN_MEMORY_DUAL_PORT 0
#define SGDMA_TX0_M_READ_MAIN_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TX0_M_READ_MAIN_MEMORY_INIT_CONTENTS_FILE "nios_system_main_memory"
#define SGDMA_TX0_M_READ_MAIN_MEMORY_INIT_MEM_CONTENT 1
#define SGDMA_TX0_M_READ_MAIN_MEMORY_INSTANCE_ID "NONE"
#define SGDMA_TX0_M_READ_MAIN_MEMORY_IRQ -1
#define SGDMA_TX0_M_READ_MAIN_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TX0_M_READ_MAIN_MEMORY_NAME "/dev/main_memory"
#define SGDMA_TX0_M_READ_MAIN_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_TX0_M_READ_MAIN_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TX0_M_READ_MAIN_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_TX0_M_READ_MAIN_MEMORY_SINGLE_CLOCK_OP 0
#define SGDMA_TX0_M_READ_MAIN_MEMORY_SIZE_MULTIPLE 1
#define SGDMA_TX0_M_READ_MAIN_MEMORY_SIZE_VALUE 307200
#define SGDMA_TX0_M_READ_MAIN_MEMORY_SPAN 307200
#define SGDMA_TX0_M_READ_MAIN_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_TX0_M_READ_MAIN_MEMORY_WRITABLE 1


/*
 * main_memory configuration as viewed by sgdma_tx1_m_read
 *
 */

#define SGDMA_TX1_M_READ_MAIN_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_TX1_M_READ_MAIN_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_TX1_M_READ_MAIN_MEMORY_BASE 0x80000
#define SGDMA_TX1_M_READ_MAIN_MEMORY_CONTENTS_INFO ""
#define SGDMA_TX1_M_READ_MAIN_MEMORY_DUAL_PORT 0
#define SGDMA_TX1_M_READ_MAIN_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TX1_M_READ_MAIN_MEMORY_INIT_CONTENTS_FILE "nios_system_main_memory"
#define SGDMA_TX1_M_READ_MAIN_MEMORY_INIT_MEM_CONTENT 1
#define SGDMA_TX1_M_READ_MAIN_MEMORY_INSTANCE_ID "NONE"
#define SGDMA_TX1_M_READ_MAIN_MEMORY_IRQ -1
#define SGDMA_TX1_M_READ_MAIN_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TX1_M_READ_MAIN_MEMORY_NAME "/dev/main_memory"
#define SGDMA_TX1_M_READ_MAIN_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_TX1_M_READ_MAIN_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TX1_M_READ_MAIN_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_TX1_M_READ_MAIN_MEMORY_SINGLE_CLOCK_OP 0
#define SGDMA_TX1_M_READ_MAIN_MEMORY_SIZE_MULTIPLE 1
#define SGDMA_TX1_M_READ_MAIN_MEMORY_SIZE_VALUE 307200
#define SGDMA_TX1_M_READ_MAIN_MEMORY_SPAN 307200
#define SGDMA_TX1_M_READ_MAIN_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_TX1_M_READ_MAIN_MEMORY_WRITABLE 1


/*
 * sgdma_rx0 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_rx0 altera_avalon_sgdma
#define SGDMA_RX0_ADDRESS_WIDTH 32
#define SGDMA_RX0_ALWAYS_DO_MAX_BURST 1
#define SGDMA_RX0_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_RX0_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_RX0_BASE 0x1038c0
#define SGDMA_RX0_BURST_DATA_WIDTH 8
#define SGDMA_RX0_BURST_TRANSFER 0
#define SGDMA_RX0_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_RX0_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_RX0_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_RX0_CONTROL_DATA_WIDTH 8
#define SGDMA_RX0_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_RX0_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_RX0_DESCRIPTOR_READ_BURST 0
#define SGDMA_RX0_DESC_DATA_WIDTH 32
#define SGDMA_RX0_HAS_READ_BLOCK 0
#define SGDMA_RX0_HAS_WRITE_BLOCK 1
#define SGDMA_RX0_IN_ERROR_WIDTH 6
#define SGDMA_RX0_IRQ 1
#define SGDMA_RX0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_RX0_NAME "/dev/sgdma_rx0"
#define SGDMA_RX0_OUT_ERROR_WIDTH 0
#define SGDMA_RX0_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_RX0_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_RX0_SPAN 64
#define SGDMA_RX0_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_RX0_STREAM_DATA_WIDTH 32
#define SGDMA_RX0_SYMBOLS_PER_BEAT 4
#define SGDMA_RX0_TYPE "altera_avalon_sgdma"
#define SGDMA_RX0_UNALIGNED_TRANSFER 0
#define SGDMA_RX0_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_RX0_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_rx1 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_rx1 altera_avalon_sgdma
#define SGDMA_RX1_ADDRESS_WIDTH 32
#define SGDMA_RX1_ALWAYS_DO_MAX_BURST 1
#define SGDMA_RX1_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_RX1_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_RX1_BASE 0x103840
#define SGDMA_RX1_BURST_DATA_WIDTH 8
#define SGDMA_RX1_BURST_TRANSFER 0
#define SGDMA_RX1_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_RX1_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_RX1_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_RX1_CONTROL_DATA_WIDTH 8
#define SGDMA_RX1_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_RX1_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_RX1_DESCRIPTOR_READ_BURST 0
#define SGDMA_RX1_DESC_DATA_WIDTH 32
#define SGDMA_RX1_HAS_READ_BLOCK 0
#define SGDMA_RX1_HAS_WRITE_BLOCK 1
#define SGDMA_RX1_IN_ERROR_WIDTH 6
#define SGDMA_RX1_IRQ 3
#define SGDMA_RX1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_RX1_NAME "/dev/sgdma_rx1"
#define SGDMA_RX1_OUT_ERROR_WIDTH 0
#define SGDMA_RX1_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_RX1_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_RX1_SPAN 64
#define SGDMA_RX1_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_RX1_STREAM_DATA_WIDTH 32
#define SGDMA_RX1_SYMBOLS_PER_BEAT 4
#define SGDMA_RX1_TYPE "altera_avalon_sgdma"
#define SGDMA_RX1_UNALIGNED_TRANSFER 0
#define SGDMA_RX1_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_RX1_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_tx0 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_tx0 altera_avalon_sgdma
#define SGDMA_TX0_ADDRESS_WIDTH 32
#define SGDMA_TX0_ALWAYS_DO_MAX_BURST 1
#define SGDMA_TX0_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_TX0_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_TX0_BASE 0x103880
#define SGDMA_TX0_BURST_DATA_WIDTH 8
#define SGDMA_TX0_BURST_TRANSFER 0
#define SGDMA_TX0_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_TX0_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_TX0_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_TX0_CONTROL_DATA_WIDTH 8
#define SGDMA_TX0_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_TX0_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_TX0_DESCRIPTOR_READ_BURST 0
#define SGDMA_TX0_DESC_DATA_WIDTH 32
#define SGDMA_TX0_HAS_READ_BLOCK 1
#define SGDMA_TX0_HAS_WRITE_BLOCK 0
#define SGDMA_TX0_IN_ERROR_WIDTH 0
#define SGDMA_TX0_IRQ 2
#define SGDMA_TX0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_TX0_NAME "/dev/sgdma_tx0"
#define SGDMA_TX0_OUT_ERROR_WIDTH 1
#define SGDMA_TX0_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_TX0_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_TX0_SPAN 64
#define SGDMA_TX0_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_TX0_STREAM_DATA_WIDTH 32
#define SGDMA_TX0_SYMBOLS_PER_BEAT 4
#define SGDMA_TX0_TYPE "altera_avalon_sgdma"
#define SGDMA_TX0_UNALIGNED_TRANSFER 0
#define SGDMA_TX0_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_TX0_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_tx1 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_tx1 altera_avalon_sgdma
#define SGDMA_TX1_ADDRESS_WIDTH 32
#define SGDMA_TX1_ALWAYS_DO_MAX_BURST 1
#define SGDMA_TX1_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_TX1_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_TX1_BASE 0x103800
#define SGDMA_TX1_BURST_DATA_WIDTH 8
#define SGDMA_TX1_BURST_TRANSFER 0
#define SGDMA_TX1_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_TX1_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_TX1_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_TX1_CONTROL_DATA_WIDTH 8
#define SGDMA_TX1_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_TX1_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_TX1_DESCRIPTOR_READ_BURST 0
#define SGDMA_TX1_DESC_DATA_WIDTH 32
#define SGDMA_TX1_HAS_READ_BLOCK 1
#define SGDMA_TX1_HAS_WRITE_BLOCK 0
#define SGDMA_TX1_IN_ERROR_WIDTH 0
#define SGDMA_TX1_IRQ 4
#define SGDMA_TX1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_TX1_NAME "/dev/sgdma_tx1"
#define SGDMA_TX1_OUT_ERROR_WIDTH 1
#define SGDMA_TX1_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_TX1_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_TX1_SPAN 64
#define SGDMA_TX1_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_TX1_STREAM_DATA_WIDTH 32
#define SGDMA_TX1_SYMBOLS_PER_BEAT 4
#define SGDMA_TX1_TYPE "altera_avalon_sgdma"
#define SGDMA_TX1_UNALIGNED_TRANSFER 0
#define SGDMA_TX1_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_TX1_WRITE_BURSTCOUNT_WIDTH 4


/*
 * tse0 configuration
 *
 */

#define ALT_MODULE_CLASS_tse0 altera_eth_tse
#define TSE0_BASE 0x103400
#define TSE0_ENABLE_MACLITE 0
#define TSE0_FIFO_WIDTH 32
#define TSE0_IRQ -1
#define TSE0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TSE0_IS_MULTICHANNEL_MAC 0
#define TSE0_MACLITE_GIGE 0
#define TSE0_MDIO_SHARED 0
#define TSE0_NAME "/dev/tse0"
#define TSE0_NUMBER_OF_CHANNEL 1
#define TSE0_NUMBER_OF_MAC_MDIO_SHARED 1
#define TSE0_PCS 0
#define TSE0_PCS_ID 0
#define TSE0_PCS_SGMII 0
#define TSE0_RECEIVE_FIFO_DEPTH 2048
#define TSE0_REGISTER_SHARED 0
#define TSE0_RGMII 1
#define TSE0_SPAN 1024
#define TSE0_TRANSMIT_FIFO_DEPTH 2048
#define TSE0_TYPE "altera_eth_tse"
#define TSE0_USE_MDIO 1


/*
 * tse1 configuration
 *
 */

#define ALT_MODULE_CLASS_tse1 altera_eth_tse
#define TSE1_BASE 0x103000
#define TSE1_ENABLE_MACLITE 0
#define TSE1_FIFO_WIDTH 32
#define TSE1_IRQ -1
#define TSE1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TSE1_IS_MULTICHANNEL_MAC 0
#define TSE1_MACLITE_GIGE 0
#define TSE1_MDIO_SHARED 0
#define TSE1_NAME "/dev/tse1"
#define TSE1_NUMBER_OF_CHANNEL 1
#define TSE1_NUMBER_OF_MAC_MDIO_SHARED 1
#define TSE1_PCS 0
#define TSE1_PCS_ID 0
#define TSE1_PCS_SGMII 0
#define TSE1_RECEIVE_FIFO_DEPTH 2048
#define TSE1_REGISTER_SHARED 0
#define TSE1_RGMII 1
#define TSE1_SPAN 1024
#define TSE1_TRANSMIT_FIFO_DEPTH 2048
#define TSE1_TYPE "altera_eth_tse"
#define TSE1_USE_MDIO 1

#endif /* __SYSTEM_H_ */
